name: s_timesheet_mobile
description: Dự án chấm công mobile S-TimeSheet ASGL

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_settings: 4.0.1+1
  intl: ^0.16.0
  table_calendar: 2.2.2
  cupertino_icons: ^0.1.2
  qr_flutter: ^3.2.0
  location: ^3.0.0
  permission_handler: ^5.0.0
  shared_preferences: ^0.5.6+3
  #  firebase_messaging: 6.0.13
  flutter_screenutil: ^1.1.0
  hive: 1.1.1
  hive_flutter: ^0.3.0+2
  google_maps_flutter: ^0.5.27+2
  path_provider: 1.6.5
  flutter_slidable: ^0.5.4
  http: ^0.12.0+2
  camera: ^0.5.8+1
  dio: ^3.0.8
  cached_network_image: ^2.0.0
  simple_rsa: ^0.0.5
  core_asgl:
    git:
      url: git@bitbucket.org:Binhit/core_asgl.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.1
  build_runner: ^1.10.0
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
    - asset/fonts/
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: asset/fonts/Roboto-Regular.ttf

    - family: Roboto-Bold
      fonts:
        - asset: asset/fonts/Roboto-Bold.ttf

    - family: Roboto-Italic
      fonts:
        - asset: asset/fonts/Roboto-Italic.ttf

    - family: Roboto-Medium
      fonts:
        - asset: asset/fonts/Roboto-Medium.ttf
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

